_merge: deep

title: Hugolify Lab
description: "Prototipo Hugolify — laboratorio de frameworks para clientes"
author: Pablo IB

admin:
  cms: sveltiacms
  branch: main
  repo: pabloalgo/hugolify-lab
  base_url: https://sveltia-cms-auth.pabloillescasburriel.workers.dev
